# Generated by Django 3.2.7 on 2022-11-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_main', '0007_auto_20221106_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connected',
        ),
    ]
