# Generated by Django 3.2.7 on 2022-11-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_main', '0008_remove_profile_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
