# Generated by Django 3.2.7 on 2022-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_main', '0009_connect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
